services:
  - type: web
    name: fleet-api-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1 