services:
  - type: web
    name: fleet-api-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: fleet-api-bot
          property: url
    healthCheckPath: /health
    plan: free 