services:
  - type: web
    name: fleet-api-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 3000
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /
    buildCommand: npm install
    startCommand: npm start 